global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nestjs-app' # ← New job add karo
    static_configs:
      - targets: ['host.docker.internal:7000'] # ← NestJS app target
    metrics_path: '/metrics' # ← Metrics endpoint
    scrape_interval: 5s # ← Trading app ke liye frequent
